// <auto-generated />
public static class LocKeys
{
    public static class AbilityUI
    {
        public const int axeDamage1Name = 4194405;
        public const int axeDurability1Name = 4194407;
        public const int stamina1Name = 4194409;
        public const int logValue1Name = 4194411;
        public const int movementSpeedName = 4194413;
        public const int stamina2Name = 4194415;
        public const int fatigueMaxIncrease1Name = 4194417;
        public const int fatigueMaxIncrease2Name = 4194419;
        public const int fatigueMaxIncrease3Name = 4194421;
        public const int sourceOfSpeed1Name = 4194423;
        public const int verdantPlainsOvergrowthName = 4194425;
        public const int woodenTransportBoxExpansion1Name = 4194427;
        public const int inventoryExpansion1Name = 4194429;
        public const int woodenTransportBoxExpansion2Name = 4194431;
        public const int logCapacityIncrease1Name = 4194433;
        public const int logCapacityIncrease2Name = 4194435;
        public const int sawmillLogStorageExpansion1Name = 4194437;
        public const int logProcessingSpeed1Name = 4194439;
        public const int sawmillLogStorageExpansion2Name = 4194441;
        public const int powerSupplyName = 4194443;
        public const int logProcessingSpeed2Name = 4194445;
        public const int bountifulTree1Name = 4194447;
        public const int fascinatingLogChance1Name = 4194449;
        public const int pickupRange1Name = 4194451;
        public const int logValue2Name = 4194453;
        public const int bountifulTree2Name = 4194455;
        public const int shockwave1Name = 4194457;
        public const int axeDamage2Name = 4194459;
        public const int axeAttackSpeed1Name = 4194461;
        public const int axeDamage3Name = 4194463;
        public const int axeCriticalChance1Name = 4194465;
        public const int shockwaveDamage1Name = 4194467;
        public const int shockwaveRange1Name = 4194469;
        public const int axeCriticalDamage1Name = 4194471;
        public const int shockwave2Name = 4194473;
        public const int shockwaveDamage2Name = 4194475;
        public const int shockwaveRange2Name = 4194477;
        public const int efficientMovement1Name = 4194479;
        public const int sporeShieldRegenBlock1Name = 4194481;
        public const int steelAxe1Name = 4194483;
        public const int commonLevel = 4203304;
        public const int commonFree = 4203305;
        public const int commonMaxLevel = 4203306;
        public const int abilityDescriptionInventoryExpansion = 4203404;
        public const int abilityDescriptionLogCapacityIncrease = 4203405;
        public const int abilityDescriptionSawmillLogStorageExpansion = 4203406;
        public const int abilityDescriptionLogProcessingSpeed = 4203407;
        public const int abilityDescriptionAxeDamage = 4203408;
        public const int abilityDescriptionLogValue = 4203409;
        public const int abilityDescriptionVerdantPlainsOvergrowth = 4203410;
        public const int abilityDescriptionStamina = 4203411;
        public const int abilityDescriptionStaminaMaxIncrease = 4203412;
        public const int abilityDescriptionConveyorSpeed = 4203413;
        public const int abilityDescriptionEfficientMovement = 4203414;
        public const int abilityDescriptionShockwave = 4203415;
        public const int abilityDescriptionAxeRange = 4203416;
        public const int abilityDescriptionAxeDurability = 4203417;
        public const int abilityDescriptionSteelAxe = 4203418;
        public const int abilityDescriptionPowerSupply = 4203419;
        public const int abilityDescriptionPickupRange = 4203420;
        public const int abilityDescriptionFascinatingLogChance = 4203421;
        public const int abilityDescriptionMovementSpeed = 4203422;
        public const int abilityDescriptionShockwaveDamage = 4203423;
        public const int abilityDescriptionShockwaveRange = 4203424;
        public const int abilityDescriptionAxeAttackSpeed = 4203425;
        public const int abilityDescriptionWoodenTransportBox = 4203426;
    }

    public static class MenuPopupUI
    {
        public const int information = 2097153;
        public const int mapName1 = 2097154;
        public const int mapName2 = 2097155;
        public const int mapName3 = 2097156;
        public const int mapName4 = 2097157;
        public const int mapName5 = 2097158;
    }

    public static class ResultUI
    {
        public const int resultTitle = 6291457;
        public const int treeKillCountZero = 6291458;
        public const int treeKillCountLow = 6291459;
        public const int treeKillCountMiddle = 6291460;
        public const int treeKillCountHigh = 6291461;
        public const int acquiredLogsHeader = 6291462;
        public const int emptyAcquiredLogs = 6291463;
        public const int containerStateHeader = 6291464;
    }

    public static class WarningUI
    {
        public const int mainText = 8388609;
        public const int subText = 8388610;
    }

}
