// <auto-generated />
public static class LocKeys
{
    public static class AbilityUI
    {
        public const int axeDamage1Name = 4194405;
        public const int axeDurability1Name = 4194407;
        public const int stamina1Name = 4194409;
        public const int logValue1Name = 4194411;
        public const int movementSpeedName = 4194413;
        public const int stamina2Name = 4194415;
        public const int fatigueMaxIncrease1Name = 4194417;
        public const int fatigueMaxIncrease2Name = 4194419;
        public const int fatigueMaxIncrease3Name = 4194421;
        public const int sourceOfSpeed1Name = 4194423;
        public const int wideGreenForestOvergrowthName = 4194425;
        public const int woodenTransportBoxExpansion1Name = 4194427;
        public const int inventoryExpansion1Name = 4194429;
        public const int woodenTransportBoxExpansion2Name = 4194431;
        public const int logCapacityIncrease1Name = 4194433;
        public const int logCapacityIncrease2Name = 4194435;
        public const int sawmillLogStorageExpansion1Name = 4194437;
        public const int logProcessingSpeed1Name = 4194439;
        public const int sawmillLogStorageExpansion2Name = 4194441;
        public const int powerSupplyName = 4194443;
        public const int logProcessingSpeed2Name = 4194445;
        public const int bountifulTree1Name = 4194447;
        public const int goldTreeChanceName = 4194449;
        public const int pickupRange1Name = 4194451;
        public const int logValue2Name = 4194453;
        public const int bountifulTree2Name = 4194455;
        public const int shockwave1Name = 4194457;
        public const int axeDamage2Name = 4194459;
        public const int axeAttackSpeed1Name = 4194461;
        public const int axeDamage3Name = 4194463;
        public const int axeCriticalChance1Name = 4194465;
        public const int shockwaveDamage1Name = 4194467;
        public const int shockwaveRange1Name = 4194469;
        public const int axeCriticalDamage1Name = 4194471;
        public const int shockwave2Name = 4194473;
        public const int shockwaveDamage2Name = 4194475;
        public const int shockwaveRange2Name = 4194477;
        public const int efficientMovement1Name = 4194479;
        public const int sporeShieldRegenBlock1Name = 4194481;
        public const int steelAxe1Name = 4194483;
        public const int testNodeName = 4194484;
        public const int shockwaveDamage3Name = 4194485;
        public const int shockWaveEnforcementName = 4194486;
        public const int shockWaveCriticalName = 4194487;
        public const int shockwave3Name = 4194488;
        public const int shockWaveMasteryName = 4194489;
        public const int shockwaveRange3Name = 4194490;
        public const int axeDurability2Name = 4194491;
        public const int steelAxe2Name = 4194492;
        public const int axeRange1Name = 4194493;
        public const int multiAttackName = 4194494;
        public const int axeDamage4Name = 4194495;
        public const int axeCriticalChance2Name = 4194496;
        public const int axeCriticalDamage2Name = 4194497;
        public const int boomerang1Name = 4194498;
        public const int boomerangDamage1Name = 4194499;
        public const int boomerangRange1Name = 4194500;
        public const int logValue3Name = 4194501;
        public const int bountifulTree3Name = 4194502;
        public const int fluffySporeForestOverGrowthName = 4194503;
        public const int fascinatingLogChance2Name = 4194504;
        public const int treeVitamin1Name = 4194505;
        public const int logProcessingSpeed3Name = 4194506;
        public const int processLineExpand1Name = 4194507;
        public const int conveyorSpeed1Name = 4194508;
        public const int itemTransferSpeedUP1Name = 4194509;
        public const int fatigueMaxIncrease4Name = 4194510;
        public const int sourceOfStamina1Name = 4194511;
        public const int sporeShieldCut1Name = 4194512;
        public const int sporeShieldRegenBlock2Name = 4194513;
        public const int sporeShieldPenetration1Name = 4194514;
        public const int sporeShieldCut2Name = 4194515;
        public const int sporeShieldPenetration2Name = 4194516;
        public const int shieldExplosionUnlockName = 4194517;
        public const int shieldExplosionDamage1Name = 4194518;
        public const int shieldExplosionRange1Name = 4194519;
        public const int logProcessingSpeed4Name = 4194520;
        public const int sporeShieldCut3Name = 4194521;
        public const int sporeShieldPenetration3Name = 4194522;
        public const int sporeShieldRegenBlock3Name = 4194523;
        public const int weakPointHit1Name = 4194524;
        public const int boomerangDamage2Name = 4194525;
        public const int boomerangRange2Name = 4194526;
        public const int boomerang2Name = 4194527;
        public const int boomerangCriticalName = 4194528;
        public const int boomerangAttackSpeed1Name = 4194529;
        public const int fatigueMaxIncrease5Name = 4194530;
        public const int stamina3Name = 4194531;
        public const int staminaRecoverName = 4194532;
        public const int boomerangDamage3Name = 4194533;
        public const int boomerangRange3Name = 4194534;
        public const int boomerangDistanceName = 4194535;
        public const int boomerangCooldownReductionName = 4194536;
        public const int boomerangAttackSpeed2Name = 4194537;
        public const int shieldExplosionResearchName = 4194538;
        public const int logValue4Name = 4194539;
        public const int bountifulTree4Name = 4194540;
        public const int starrootForestOverGrowthName = 4194541;
        public const int axeDamage5Name = 4194542;
        public const int boomerang3Name = 4194543;
        public const int axeAttackSpeed2Name = 4194544;
        public const int attackRythm1Name = 4194545;
        public const int axeDurability3Name = 4194546;
        public const int steelAxe3Name = 4194547;
        public const int movementSpeed2Name = 4194548;
        public const int efficientMovement2Name = 4194549;
        public const int pickupRange2Name = 4194550;
        public const int constellationManifestUnlockName = 4194551;
        public const int starPathSpeedBoost1Name = 4194552;
        public const int starMarkDamage1Name = 4194553;
        public const int constellationDamage1Name = 4194554;
        public const int commonLevel = 4203304;
        public const int commonFree = 4203305;
        public const int commonMaxLevel = 4203306;
        public const int commonToUnlock = 4203307;
        public const int commonUnlockComplete = 4203308;
        public const int keyGuideAbilityUpgrade = 4203309;
        public const int keyGuideDragToMove = 4203310;
        public const int keyGuideZoom = 4203311;
        public const int abilityDescriptionInventoryExpansion = 4203404;
        public const int abilityDescriptionLogCapacityIncrease = 4203405;
        public const int abilityDescriptionSawmillLogStorageExpansion = 4203406;
        public const int abilityDescriptionLogProcessingSpeed = 4203407;
        public const int abilityDescriptionAxeDamage = 4203408;
        public const int abilityDescriptionLogValue = 4203409;
        public const int abilityDescriptionWideGreenForestOvergrowth = 4203410;
        public const int abilityDescriptionStamina = 4203411;
        public const int abilityDescriptionStaminaMaxIncrease = 4203412;
        public const int abilityDescriptionConveyorSpeed = 4203413;
        public const int abilityDescriptionEfficientMovement = 4203414;
        public const int abilityDescriptionShockwave = 4203415;
        public const int abilityDescriptionAxeRange = 4203416;
        public const int abilityDescriptionAxeDurability = 4203417;
        public const int abilityDescriptionSteelAxe = 4203418;
        public const int abilityDescriptionPowerSupply = 4203419;
        public const int abilityDescriptionPickupRange = 4203420;
        public const int abilityDescriptionFascinatingLogChance = 4203421;
        public const int abilityDescriptionMovementSpeed = 4203422;
        public const int abilityDescriptionShockwaveDamage = 4203423;
        public const int abilityDescriptionShockwaveRange = 4203424;
        public const int abilityDescriptionAxeAttackSpeed = 4203425;
        public const int abilityDescriptionWoodenTransportBox = 4203426;
        public const int abilityDescriptionAxeCriticalChance = 4203427;
        public const int abilityDescriptionAxeCriticalDamage = 4203428;
        public const int abilityDescriptionSourceOfSpeed = 4203429;
        public const int abilityDescriptionSporeShieldRegenBlock = 4203430;
        public const int abilityDescriptionShockWaveEnforcement = 4203431;
        public const int abilityDescriptionShockWaveCritical = 4203432;
        public const int abilityDescriptionShockWaveMastery = 4203433;
        public const int abilityDescriptionMultiAttack = 4203434;
        public const int abilityDescriptionBoomerang = 4203435;
        public const int abilityDescriptionBoomerangDamage = 4203436;
        public const int abilityDescriptionBoomerangRange = 4203437;
        public const int abilityDescriptionFluffySporeForestOverGrowth = 4203438;
        public const int abilityDescriptionTreeVitamin = 4203439;
        public const int abilityDescriptionProcessLineExpand = 4203440;
        public const int abilityDescriptionLogProcessorSpeedUp = 4203441;
        public const int abilityDescriptionSourceOfStamina = 4203442;
        public const int abilityDescriptionSporeShieldCut = 4203443;
        public const int abilityDescriptionSporeShieldPenetration = 4203444;
        public const int abilityDescriptionItemTransferSpeedUP = 4203445;
        public const int abilityDescriptionShieldExplosionUnlock = 4203446;
        public const int abilityDescriptionShieldExplosionDamage = 4203447;
        public const int abilityDescriptionShieldExplosionRange = 4203448;
        public const int abilityDescriptionWeakPointHit = 4203449;
        public const int abilityDescriptionBoomerangCritical = 4203450;
        public const int abilityDescriptionBoomerangAttackSpeed = 4203451;
        public const int abilityDescriptionStaminaRecover = 4203452;
        public const int abilityDescriptionBoomerangDistance = 4203453;
        public const int abilityDescriptionBoomerangCooldownReduction = 4203454;
        public const int abilityDescriptionShieldExplosionResearch = 4203455;
        public const int abilityDescriptionStarrootForestOverGrowth = 4203456;
        public const int abilityDescriptionAttackRythm = 4203457;
        public const int abilityDescriptionConstellationManifestUnlock = 4203458;
        public const int abilityDescriptionStarPathSpeedBoost = 4203459;
        public const int abilityDescriptionStarMarkDamage = 4203460;
        public const int abilityDescriptionConstellationDamage = 4203461;
    }

    public static class DemoNoticeUI
    {
        public const int title = 29360129;
        public const int description = 29360130;
    }

    public static class EquipmentHUD
    {
        public const int axeUse = 25165825;
    }

    public static class EscapeMenuUI
    {
        public const int resume = 27262977;
        public const int option = 27262978;
        public const int mainMenu = 27262979;
        public const int exitGame = 27262980;
        public const int exitGameWarning = 27262981;
        public const int mainMenuWarning = 27262982;
    }

    public static class InventoryUI
    {
        public const int open = 23068673;
    }

    public static class LootTooltipUI
    {
        public const int foundbox = 20971521;
        public const int sporepotion = 20971522;
        public const int starcompass = 20971523;
        public const int nameLostandfoundbox = 20971524;
        public const int nameSporepotion = 20971525;
        public const int nameStarcompass = 20971526;
        public const int nameObsidiancharm = 20971527;
    }

    public static class MainMenuUI
    {
        public const int newGame = 16777217;
        public const int loadGame = 16777218;
        public const int options = 16777219;
        public const int credits = 16777220;
        public const int exit = 16777221;
        public const int pressAnyKey = 16777315;
        public const int newGameWarning = 16777222;
        public const int dotText = 16777223;
    }

    public static class MenuPopupUI
    {
        public const int information = 2097153;
        public const int mapName1 = 2097154;
        public const int mapName2 = 2097155;
        public const int mapName3 = 2097156;
        public const int mapName4 = 2097157;
        public const int mapName5 = 2097158;
    }

    public static class MessageHUD
    {
        public const int forestNoneTitle = 12582913;
        public const int forestInTownTitle = 12582914;
        public const int forestWideGreenForest1Title = 12582915;
        public const int forestWideGreenForest2Title = 12582916;
        public const int forestWideGreenForest3Title = 12582917;
        public const int forestFluffySporeForest1Title = 12582918;
        public const int forestFluffySporeForest2Title = 12582919;
        public const int forestFluffySporeForest3Title = 12582920;
        public const int forestStarrootForest1Title = 12582921;
        public const int forestStarrootForest2Title = 12582922;
        public const int forestStarrootForest3Title = 12582923;
        public const int forestMagmaForest1Title = 12582924;
        public const int forestMagmaForest2Title = 12582925;
        public const int forestMagmaForest3Title = 12582926;
        public const int dungeonStateNoneSubText = 12583013;
        public const int dungeonStateStage1Idle0SubText = 12583014;
        public const int dungeonStateStage1Idle1SubText = 12583015;
        public const int dungeonStateStage1Idle2SubText = 12583016;
        public const int dungeonStateStage1Idle3SubText = 12583017;
        public const int dungeonStateStage2Idle0SubText = 12583018;
        public const int dungeonStateStage2Idle1SubText = 12583019;
        public const int dungeonStateStage2Idle2SubText = 12583020;
        public const int dungeonStateStage3Idle0SubText = 12583021;
        public const int dungeonStateStage3Idle1SubText = 12583022;
        public const int dungeonStateStage3Idle2SubText = 12583023;
        public const int dungeonStateStage4Idle0SubText = 12583024;
        public const int dungeonStateStage4Idle1SubText = 12583025;
        public const int dungeonStateStage4Idle2SubText = 12583026;
    }

    public static class NavigationTreePropUI
    {
        public const int oakTree = 14680065;
        public const int pineTree = 14680066;
        public const int birchTree = 14680067;
        public const int sporepuffTree = 14680068;
        public const int fluffyMyceliumTree = 14680069;
        public const int bellpineTree = 14680070;
        public const int starrootTree = 14680071;
        public const int moonhaloTree = 14680072;
        public const int galaxygrainTree = 14680073;
        public const int cinderTree = 14680074;
        public const int lavasapTree = 14680075;
        public const int obsidianTree = 14680076;
    }

    public static class OpeningProductionUI
    {
        public const int openingMonologue0 = 33554433;
        public const int openingMonologue1 = 33554434;
        public const int openingMonologue2 = 33554435;
        public const int openingMonologue3 = 33554436;
    }

    public static class OptionUI
    {
        public const int windowed = 18874469;
        public const int fullscreen = 18874470;
        public const int on = 18874471;
        public const int off = 18874472;
        public const int vSync = 18874473;
        public const int unlimited = 18874474;
        public const int languageKorean = 18874475;
        public const int languageEnglish = 18874476;
        public const int languageChineseSimplified = 18874477;
        public const int languageChineseTraditional = 18874478;
        public const int languageJapanese = 18874479;
        public const int language = 18874569;
        public const int resolution = 18874570;
        public const int windowMode = 18874571;
        public const int fPS = 18874572;
        public const int pauseOnUnfocus = 18874573;
        public const int cameraShake = 18874574;
        public const int crosshairBrightness = 18874575;
        public const int chromaticAberration = 18874576;
        public const int screenBrightness = 18874577;
        public const int screenSaturation = 18874578;
        public const int masterVolume = 18874579;
        public const int bGMVolume = 18874580;
        public const int sFXVolume = 18874581;
        public const int tabGameplay = 18874669;
        public const int tabSound = 18874670;
        public const int tabGraphic = 18874671;
        public const int tabControl = 18874672;
        public const int moveUp = 18874673;
        public const int moveDown = 18874674;
        public const int moveLeft = 18874675;
        public const int moveRight = 18874676;
        public const int inventory = 18874677;
        public const int interaction = 18874678;
        public const int attack = 18874679;
        public const int potionKey = 18874680;
        public const int pressKeyPrompt = 18874681;
        public const int resetAllWarning = 18874682;
        public const int close = 18874683;
        public const int resetToDefault = 18874684;
        public const int apply = 18874685;
        public const int unsavedChangesWarning = 18874686;
    }

    public static class ResultUI
    {
        public const int resultTitle = 6291457;
        public const int treeKillCountZero = 6291458;
        public const int treeKillCountLow = 6291459;
        public const int treeKillCountMiddle = 6291460;
        public const int treeKillCountHigh = 6291461;
        public const int acquiredLogsHeader = 6291462;
        public const int emptyAcquiredLogs = 6291463;
        public const int containerStateHeader = 6291464;
    }

    public static class SpeechBubbleUI
    {
        public const int inventoryFull = 10485761;
        public const int itemCantAcquired = 10485762;
        public const int axeDurabilityEmpty = 10485763;
    }

    public static class TutorialQuestUI
    {
        public const int cutTreeTitle = 31457281;
        public const int fillOffroadContainerTitle = 31457282;
        public const int fillOffroadContainerDesc = 31457283;
        public const int goHomeBeforeExhaustedTitle = 31457284;
        public const int putItemsInLogContainerTitle = 31457285;
        public const int receiveMoneyTitle = 31457286;
        public const int upgradeAxeTitle = 31457287;
        public const int startNewLoggingTitle = 31457288;
        public const int unlockNewRegionTitle = 31457289;
    }

    public static class WarningUI
    {
        public const int mainText = 8388609;
        public const int subText = 8388610;
    }

}
