// <auto-generated />
public static class LocKeys
{
    public static class AbilityUI
    {
        public const int axeDamage1Name = 4194405;
        public const int axeDamage1Description = 4194406;
        public const int axeDurability1Name = 4194407;
        public const int axeDurability1Description = 4194408;
        public const int stamina1Name = 4194409;
        public const int stamina1Description = 4194410;
        public const int logValue1Name = 4194411;
        public const int logValue1Description = 4194412;
        public const int movementSpeedName = 4194413;
        public const int movementSpeedDescription = 4194414;
        public const int stamina2Name = 4194415;
        public const int stamina2Description = 4194416;
        public const int fatigueMaxIncrease1Name = 4194417;
        public const int fatigueMaxIncrease1Description = 4194418;
        public const int fatigueMaxIncrease2Name = 4194419;
        public const int fatigueMaxIncrease2Description = 4194420;
        public const int fatigueMaxIncrease3Name = 4194421;
        public const int fatigueMaxIncrease3Description = 4194422;
        public const int sourceOfSpeed1Name = 4194423;
        public const int sourceOfSpeed1Description = 4194424;
        public const int verdantPlainsOvergrowthName = 4194425;
        public const int verdantPlainsOvergrowthDescription = 4194426;
        public const int woodenTransportBoxExpansion1Name = 4194427;
        public const int woodenTransportBoxExpansion1Description = 4194428;
        public const int inventoryExpansion1Name = 4194429;
        public const int inventoryExpansion1Description = 4194430;
        public const int woodenTransportBoxExpansion2Name = 4194431;
        public const int woodenTransportBoxExpansion2Description = 4194432;
        public const int logCapacityIncrease1Name = 4194433;
        public const int logCapacityIncrease1Description = 4194434;
        public const int logCapacityIncrease2Name = 4194435;
        public const int logCapacityIncrease2Description = 4194436;
        public const int sawmillLogStorageExpansion1Name = 4194437;
        public const int sawmillLogStorageExpansion1Description = 4194438;
        public const int logProcessingSpeed1Name = 4194439;
        public const int logProcessingSpeed1Description = 4194440;
        public const int sawmillLogStorageExpansion2Name = 4194441;
        public const int sawmillLogStorageExpansion2Description = 4194442;
        public const int powerSupplyName = 4194443;
        public const int powerSupplyDescription = 4194444;
        public const int logProcessingSpeed2Name = 4194445;
        public const int logProcessingSpeed2Description = 4194446;
        public const int bountifulTree1Name = 4194447;
        public const int bountifulTree1Description = 4194448;
        public const int fascinatingLogChance1Name = 4194449;
        public const int fascinatingLogChance1Description = 4194450;
        public const int pickupRange1Name = 4194451;
        public const int pickupRange1Description = 4194452;
        public const int logValue2Name = 4194453;
        public const int logValue2Description = 4194454;
        public const int bountifulTree2Name = 4194455;
        public const int bountifulTree2Description = 4194456;
        public const int shockwave1Name = 4194457;
        public const int shockwave1Description = 4194458;
        public const int axeDamage2Name = 4194459;
        public const int axeDamage2Description = 4194460;
        public const int axeAttackSpeed1Name = 4194461;
        public const int axeAttackSpeed1Description = 4194462;
        public const int axeDamage3Name = 4194463;
        public const int axeDamage3Description = 4194464;
        public const int axeCriticalChance1Name = 4194465;
        public const int axeCriticalChance1Description = 4194466;
        public const int shockwaveDamage1Name = 4194467;
        public const int shockwaveDamage1Description = 4194468;
        public const int shockwaveRange1Name = 4194469;
        public const int shockwaveRange1Description = 4194470;
        public const int axeCriticalDamage1Name = 4194471;
        public const int axeCriticalDamage1Description = 4194472;
        public const int shockwave2Name = 4194473;
        public const int shockwave2Description = 4194474;
        public const int shockwaveDamage2Name = 4194475;
        public const int shockwaveDamage2Description = 4194476;
        public const int shockwaveRange2Name = 4194477;
        public const int shockwaveRange2Description = 4194478;
        public const int efficientMovement1Name = 4194479;
        public const int efficientMovement1Description = 4194480;
        public const int sporeShieldRegenBlock1Name = 4194481;
        public const int sporeShieldRegenBlock1Description = 4194482;
        public const int steelAxe1Name = 4194483;
        public const int steelAxe1Description = 4194484;
        public const int commonLevel = 4203304;
        public const int commonFree = 4203305;
        public const int commonMaxLevel = 4203306;
    }

    public static class MenuPopupUI
    {
        public const int information = 2097153;
        public const int mapName1 = 2097154;
        public const int mapName2 = 2097155;
        public const int mapName3 = 2097156;
        public const int mapName4 = 2097157;
        public const int mapName5 = 2097158;
    }

}
