using System;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;
using System.Collections.Generic;

public class LocKeyGenerator
{
    private const string JsonPath = "Assets/Resources/Localization";
    private const string ExportPath = "Assets/Scripts/Application Layer/LocalizationSystem/LocKeys.cs";
    private const string MappingSOPath = "Assets/Scriptable Obj/Localization/LocalizationMapping.asset";
    private const string OldMappingSOPath1 = "Assets/Resources/Localization/LocalizationMapping.asset";
    private const string OldMappingSOPath2 = "Assets/Resources/ScriptableObject/Localization/LocalizationMapping.asset";

    [MenuItem("Tools/Localization/Generate Keys")]
    public static void Generate()
    {
        if (!Directory.Exists(JsonPath))
        {
            Debug.LogError($"[LocKeyGenerator] Path not found: {JsonPath}");
            return;
        }

        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("public static class LocKeys");
        sb.AppendLine("{");

        string[] jsonFiles = Directory.GetFiles(JsonPath, "*.json");

        List<LocalizationMapping.MappingEntry> mappingEntries = new List<LocalizationMapping.MappingEntry>();

        foreach (string filePath in jsonFiles)
        {
            string fileName = Path.GetFileNameWithoutExtension(filePath);
            string className = SanitizeName(fileName);
            string jsonText = File.ReadAllText(filePath);
            var data = JsonUtility.FromJson<LocalizationDataJson>(jsonText);

            if (data == null || data.entries == null) continue;

            sb.AppendLine($"    public static class {className}");
            sb.AppendLine("    {");
            foreach (var entry in data.entries)
            {
                if (entry.id == 0) continue;

                int key = GenerateCompositeKey(data.jsonId, entry.id);
                string identifier = !string.IsNullOrEmpty(entry.key) ? entry.key : entry.en;
                string safeName = SanitizeName(identifier);
                if (string.IsNullOrEmpty(safeName)) safeName = $"Id{entry.id}";
                
                string camelCaseName = ToCamelCase(safeName);
                
                sb.AppendLine($"        public const int {camelCaseName} = {key};");

                // 자동 매핑 등록 로직
                if (!string.IsNullOrEmpty(entry.enumType) && !string.IsNullOrEmpty(entry.enumValue))
                {
                    Type type = FindTypeInAssemblies(entry.enumType);
                    if (type != null && type.IsEnum)
                    {
                        try
                        {
                            object enumObj = Enum.Parse(type, entry.enumValue, true);
                            int enumIntVal = Convert.ToInt32(enumObj);

                            var newMapping = new LocalizationMapping.MappingEntry
                            {
                                enumTypeName = entry.enumType,
                                enumValueName = entry.enumValue,
                                enumIntValue = enumIntVal,
                                compositeKey = key
                            };
                            mappingEntries.Add(newMapping);
                        }
                        catch (Exception)
                        {
                            Debug.LogError($"[LocKeyGenerator] Enum value '{entry.enumValue}' not found in Enum Type '{entry.enumType}' for entry ID {entry.id}");
                        }
                    }
                    else
                    {
                        Debug.LogError($"[LocKeyGenerator] Enum Type '{entry.enumType}' not found in Assemblies for entry ID {entry.id}");
                    }
                }
            }
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        // 디렉토리가 없으면 생성
        string dir = Path.GetDirectoryName(ExportPath);
        if (!Directory.Exists(dir)) Directory.CreateDirectory(dir);

        File.WriteAllText(ExportPath, sb.ToString(), Encoding.UTF8);

        // ScriptableObject 매핑 파일 갱신/생성
        SaveMappingScriptableObject(mappingEntries);

        bool generatedFontCharacterSets = LocalizationFontCharacterSetGenerator.GenerateAll(false);

        AssetDatabase.Refresh();
        if (generatedFontCharacterSets)
        {
            Debug.Log("[LocKeyGenerator] Keys, mappings, and font character sets generated successfully!");
        }
        else
        {
            Debug.LogWarning("[LocKeyGenerator] Keys and mappings were generated, but font character set generation failed.");
        }
    }

    private static Type FindTypeInAssemblies(string _typeName)
    {
        var assemblies = AppDomain.CurrentDomain.GetAssemblies();
        for (int i = 0; i < assemblies.Length; i++)
        {
            Type type = assemblies[i].GetType(_typeName);
            if (type != null) return type;
        }
        return null;
    }

    private static int GenerateCompositeKey(int _jsonId, int _entryId)
    {
        return (_jsonId << 21) | (_entryId & 0x1FFFFF);
    }

    private static void SaveMappingScriptableObject(List<LocalizationMapping.MappingEntry> _mappings)
    {
        // 구 버전 에셋 파일이 남아 있으면 정리
        if (AssetDatabase.LoadAssetAtPath<LocalizationMapping>(OldMappingSOPath1) != null)
        {
            AssetDatabase.DeleteAsset(OldMappingSOPath1);
        }
        if (AssetDatabase.LoadAssetAtPath<LocalizationMapping>(OldMappingSOPath2) != null)
        {
            AssetDatabase.DeleteAsset(OldMappingSOPath2);
        }

        string dir = Path.GetDirectoryName(MappingSOPath);
        if (!Directory.Exists(dir)) Directory.CreateDirectory(dir);

        LocalizationMapping mappingAsset = AssetDatabase.LoadAssetAtPath<LocalizationMapping>(MappingSOPath);
        bool isNew = false;

        if (mappingAsset == null)
        {
            mappingAsset = ScriptableObject.CreateInstance<LocalizationMapping>();
            isNew = true;
        }

        mappingAsset.mappings.Clear();
        for (int i = 0; i < _mappings.Count; i++)
        {
            mappingAsset.mappings.Add(_mappings[i]);
        }

        if (isNew)
        {
            AssetDatabase.CreateAsset(mappingAsset, MappingSOPath);
        }
        else
        {
            EditorUtility.SetDirty(mappingAsset);
        }
        AssetDatabase.SaveAssets();
    }

    private static string SanitizeName(string _input)
    {
        if (string.IsNullOrEmpty(_input)) return string.Empty;

        // 알파벳과 숫자만 남기고 제거
        string result = Regex.Replace(_input, @"[^a-zA-Z0-9]", " ");
        string[] words = result.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);

        StringBuilder sb = new StringBuilder();
        foreach (string word in words)
        {
            if (word.Length > 0)
            {
                // 첫 글자 대문자, 나머지는 원본 유지(혹은 소문자)하여 PascalCase 생성
                sb.Append(char.ToUpper(word[0]));
                if (word.Length > 1)
                    sb.Append(word.Substring(1)); 
            }
        }

        return sb.ToString();
    }

    private static string ToCamelCase(string _input)
    {
        if (string.IsNullOrEmpty(_input)) return string.Empty;
        if (_input.Length == 1) return _input.ToLower();
        return char.ToLower(_input[0]) + _input.Substring(1);
    }
}
