using System;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

public class LocKeyGenerator
{
    private const string JsonPath = "Assets/Resources/Localization";
    private const string ExportPath = "Assets/Scripts/Application Layer/LocalizationSystem/LocKeys.cs";

    [MenuItem("Tools/Localization/Generate Keys")]
    public static void Generate()
    {
        if (!Directory.Exists(JsonPath))
        {
            Debug.LogError($"[LocKeyGenerator] Path not found: {JsonPath}");
            return;
        }

        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("public static class LocKeys");
        sb.AppendLine("{");

        var manager = new LocalizationManager();
        string[] jsonFiles = Directory.GetFiles(JsonPath, "*.json");

        foreach (string filePath in jsonFiles)
        {
            string fileName = Path.GetFileNameWithoutExtension(filePath);
            string jsonText = File.ReadAllText(filePath);
            var data = JsonUtility.FromJson<LocalizationDataJson>(jsonText);

            if (data == null || data.entries == null) continue;

            sb.AppendLine($"    // {fileName}");
            foreach (var entry in data.entries)
            {
                if (entry.id == 0) continue;

                int key = manager.GenerateKey(data.jsonId, entry.id);
                string safeName = SanitizeName(entry.en);
                if (string.IsNullOrEmpty(safeName)) safeName = $"ID_{entry.id}";
                
                sb.AppendLine($"    public const int {fileName}_{safeName} = {key};");
            }
            sb.AppendLine();
        }

        sb.AppendLine("}");

        // 디렉토리가 없으면 생성
        string dir = Path.GetDirectoryName(ExportPath);
        if (!Directory.Exists(dir)) Directory.CreateDirectory(dir);

        File.WriteAllText(ExportPath, sb.ToString(), Encoding.UTF8);
        AssetDatabase.Refresh();
        Debug.Log($"[LocKeyGenerator] Keys generated successfully at: {ExportPath}");
    }

    private static string SanitizeName(string _input)
    {
        if (string.IsNullOrEmpty(_input)) return string.Empty;

        // 알파벳과 숫자만 남기고 제거
        string result = Regex.Replace(_input, @"[^a-zA-Z0-9]", " ");
        string[] words = result.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);

        StringBuilder sb = new StringBuilder();
        foreach (string word in words)
        {
            if (word.Length > 0)
            {
                // 첫 글자 대문자, 나머지는 원본 유지(혹은 소문자)하여 PascalCase 생성
                sb.Append(char.ToUpper(word[0]));
                if (word.Length > 1)
                    sb.Append(word.Substring(1)); 
            }
        }

        return sb.ToString();
    }
}
