// <auto-generated />
public enum SoundID
{
    None = 0,
    TownBGM = 1052300792,
    WideGreenForest1BGM = 106979007,
    GetItem = 413619275,
    Cutter = -688056987,
    BoxClose = 532227752,
    BoxOpen = -1886360244,
    OffroadOut = -233868034,
    TreeDead = -794509328,
    PitchHit = 2096610066,
    TreeHit = -1641742776,
    AxeBreakingEx = 1393049894,
    AxeBreaking = -197311369,
    AxeBreakingFinal = -43994528,
    Swing = 1971635652,
    GrassFootstep = -398605290,
    GroundFootstep = 872570553,
}

public enum MixerID
{
    None = 0,
    Master = -235980376,
    BGM = 433908404,
    SFX = 1999992957,
    UI = -1090805748,
    Ambience = -1090754126,
}
